### ISSUE TITLE
Fableの使い方に慣れる

### ISSUE THREAD

**Issue by kuroyakov** [kuroyakov/fsharp-study#3]
FableはF#->Javascript変換するフレームワーク。

これによりサーバプログラムがF#で記述でき、これをnode.jsとかで動かせるのか？
またクライアントサイドのJavascript開発にも使えいないか？

有効性を含めて調査する。

**Comment by kuroyakov** [comment]
さて、まずはこれをやってみた。
```bash
> npm install -g fable-compiler
> fable test.fsx
```

変換元コード
```fsharp
printfn "hello, fable"
```

変換先コード
```js
import { fsFormat } from "fable-core/String";
fsFormat("hello, fable")(function (x) {
  console.log(x);
});
```

これをVS Codeのデバッグ実行（Node.js使用）したら、こんなエラーが発生。
```bash
node --debug-brk=33391 --nolazy test.js 
Debugger listening on [::]:33391
/Users/katsutoshikuroya/github/fsharp-study/FableStudy/test.js:1
(function (exports, require, module, __filename, __dirname) { import { fsFormat } from "fable-core/String";
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

importという構文が認識できていないみたいだ。てことはVS CodeのNode.jsではES2015のjavascriptを解釈してくれないのか？

**Comment by kuroyakov** [comment]
fableの実行時のオプションで`--module`なるものがあった、これを`--module commonjs`にすれば、普通のコードになった。
```bash
> fable --module commonjs test.fsx
```

```js
"use strict";

var _String = require("fable-core/umd/String");

(0, _String.fsFormat)("hello, fable")(function (x) {
  console.log(x);
});
```

今度はfable-coreが見つからないとエラーが出たので、これは実行時の依存モジュールとして`fable-core`が必要ってことになる。依存パッケージを記述するために`package.json`を使うことにする。

**Comment by kuroyakov** [comment]
次は複数のfsxファイルと関連付けして見る。

**Comment by kuroyakov** [comment]
結論として以下のことがわかった

1. 変換後のJavascriptを弄らない方が良い。弄るならソース側のF#のみとする
    考え方としてはF#(source)、Javascript(アセンブラ)と捉える方が良い
2. 既存のJavascriptライブラリやコードを使いたいときは`Fable.Core.JsInterop`を利用する
    詳しくはhttp://fable.io/docs/interacting.html を参照のこと
3. 既存のJavascriptライブラリは別途F#インターフェイスを作成しているものもある。`d3`や`node`など`fable-import-***`という形式で公開しているものがある。
4. 便利F#インターフェイスがなければ自分で作れば行けそうな気がする。

注意事項としては.NET Frameworkをガチに使っているとコンパイルできない場合がある。コンパイル対応状況は、http://fable.io/docs/compatibility.html を参考のこと
